name: CI
on:
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - uses: actions/cache@v3
        with:
          path: .nx/cache
          key: nx-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            nx-cache-${{ runner.os }}-

      - run: npx nx-cloud start-ci-run --distribute-on="3 linux-large-js" --agents --stop-agents-on-error

      - run: npm ci

      - uses: nrwl/nx-set-shas@v4

      # Run lint with caching
      - run: npx nx affected --target=lint --agents --parallel --max-parallel=3

      # Run build without caching
      - run: npx nx affected --target=build -c production --agents --parallel --max-parallel=3 --skip-nx-cache

      # Run tests with caching
      - run: npx nx run-many --target=test --projects=engine,shared,server-api --agents --parallel --max-parallel=3
